### ISSUE TITLE
Missing the file “./datasets/feature_loader”

### ISSUE THREAD

**Issue by zhang1hongliang** [cvlab-stonybrook/fsl-rsvae#1]
@jingyi1997 @lmhieu612 , maybe there are some questiosns about train_vae_tiered.py in the line 20 "import datasets.feature_loader as feat_loader",  there is no feature_loader.py file in the folder "datasets", please supplement the file "feature_loader.py". thank you very much.

**Comment by hieulem** [comment]
Thanks! We will upload the missing file soon

**Comment by zjrzjr666** [comment]
I had a similar problem. thank you very much.

**Comment by ShadmanRohan** [comment]
@lmhieu612 when???

**Comment by hieulem** [comment]
The latest commit should fix this. Sorry for the delay. We got caught up with deadlines.
